/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';
import PageSportRatedLeague from '../model/PageSportRatedLeague';
import PageSportRatedLeagueEntry from '../model/PageSportRatedLeagueEntry';
import SportRatedLeague from '../model/SportRatedLeague';
import SportRatedLeagueCreate from '../model/SportRatedLeagueCreate';
import SportRatedLeagueEntry from '../model/SportRatedLeagueEntry';
import SportRatedLeagueEntryCreate from '../model/SportRatedLeagueEntryCreate';
import SportRatedLeagueEntryUpdate from '../model/SportRatedLeagueEntryUpdate';

/**
* Rating service.
* @module api/RatingApi
* @version 0.1.0
*/
export default class RatingApi {

    /**
    * Constructs a new RatingApi. 
    * @alias module:api/RatingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create League
     * @param {module:model/SportRatedLeagueCreate} SportRatedLeagueCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SportRatedLeague} and HTTP response
     */
    createLeagueWithHttpInfo(SportRatedLeagueCreate) {
      let postBody = SportRatedLeagueCreate;
      // verify the required parameter 'SportRatedLeagueCreate' is set
      if (SportRatedLeagueCreate === undefined || SportRatedLeagueCreate === null) {
        throw new Error("Missing the required parameter 'SportRatedLeagueCreate' when calling createLeague");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SportRatedLeague;
      return this.apiClient.callApi(
        '/api/v1/rating/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create League
     * @param {module:model/SportRatedLeagueCreate} SportRatedLeagueCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SportRatedLeague}
     */
    createLeague(SportRatedLeagueCreate) {
      return this.createLeagueWithHttpInfo(SportRatedLeagueCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create League Entry
     * @param {Number} league_id 
     * @param {module:model/SportRatedLeagueEntryCreate} SportRatedLeagueEntryCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SportRatedLeagueEntry} and HTTP response
     */
    createLeagueEntryWithHttpInfo(league_id, SportRatedLeagueEntryCreate) {
      let postBody = SportRatedLeagueEntryCreate;
      // verify the required parameter 'league_id' is set
      if (league_id === undefined || league_id === null) {
        throw new Error("Missing the required parameter 'league_id' when calling createLeagueEntry");
      }
      // verify the required parameter 'SportRatedLeagueEntryCreate' is set
      if (SportRatedLeagueEntryCreate === undefined || SportRatedLeagueEntryCreate === null) {
        throw new Error("Missing the required parameter 'SportRatedLeagueEntryCreate' when calling createLeagueEntry");
      }

      let pathParams = {
        'league_id': league_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SportRatedLeagueEntry;
      return this.apiClient.callApi(
        '/api/v1/rating/{league_id}/entries', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create League Entry
     * @param {Number} league_id 
     * @param {module:model/SportRatedLeagueEntryCreate} SportRatedLeagueEntryCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SportRatedLeagueEntry}
     */
    createLeagueEntry(league_id, SportRatedLeagueEntryCreate) {
      return this.createLeagueEntryWithHttpInfo(league_id, SportRatedLeagueEntryCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get League
     * @param {Number} league_id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SportRatedLeague} and HTTP response
     */
    getLeagueWithHttpInfo(league_id) {
      let postBody = null;
      // verify the required parameter 'league_id' is set
      if (league_id === undefined || league_id === null) {
        throw new Error("Missing the required parameter 'league_id' when calling getLeague");
      }

      let pathParams = {
        'league_id': league_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SportRatedLeague;
      return this.apiClient.callApi(
        '/api/v1/rating/{league_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get League
     * @param {Number} league_id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SportRatedLeague}
     */
    getLeague(league_id) {
      return this.getLeagueWithHttpInfo(league_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get League Entries
     * @param {Number} league_id 
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number
     * @param {Number} [size = 50)] Page size
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PageSportRatedLeagueEntry} and HTTP response
     */
    getLeagueEntriesWithHttpInfo(league_id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'league_id' is set
      if (league_id === undefined || league_id === null) {
        throw new Error("Missing the required parameter 'league_id' when calling getLeagueEntries");
      }

      let pathParams = {
        'league_id': league_id
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PageSportRatedLeagueEntry;
      return this.apiClient.callApi(
        '/api/v1/rating/{league_id}/entries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get League Entries
     * @param {Number} league_id 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page Page number (default to 1)
     * @param {Number} opts.size Page size (default to 50)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PageSportRatedLeagueEntry}
     */
    getLeagueEntries(league_id, opts) {
      return this.getLeagueEntriesWithHttpInfo(league_id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get League Entry
     * @param {Number} league_id 
     * @param {Number} entry_id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SportRatedLeagueEntry} and HTTP response
     */
    getLeagueEntryWithHttpInfo(league_id, entry_id) {
      let postBody = null;
      // verify the required parameter 'league_id' is set
      if (league_id === undefined || league_id === null) {
        throw new Error("Missing the required parameter 'league_id' when calling getLeagueEntry");
      }
      // verify the required parameter 'entry_id' is set
      if (entry_id === undefined || entry_id === null) {
        throw new Error("Missing the required parameter 'entry_id' when calling getLeagueEntry");
      }

      let pathParams = {
        'league_id': league_id,
        'entry_id': entry_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SportRatedLeagueEntry;
      return this.apiClient.callApi(
        '/api/v1/rating/{league_id}/entries/{entry_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get League Entry
     * @param {Number} league_id 
     * @param {Number} entry_id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SportRatedLeagueEntry}
     */
    getLeagueEntry(league_id, entry_id) {
      return this.getLeagueEntryWithHttpInfo(league_id, entry_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Leagues
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number
     * @param {Number} [size = 50)] Page size
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PageSportRatedLeague} and HTTP response
     */
    getLeaguesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PageSportRatedLeague;
      return this.apiClient.callApi(
        '/api/v1/rating/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Leagues
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page Page number (default to 1)
     * @param {Number} opts.size Page size (default to 50)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PageSportRatedLeague}
     */
    getLeagues(opts) {
      return this.getLeaguesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update League Entry
     * @param {Number} league_id 
     * @param {Number} entry_id 
     * @param {module:model/SportRatedLeagueEntryUpdate} SportRatedLeagueEntryUpdate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SportRatedLeagueEntry} and HTTP response
     */
    updateLeagueEntryWithHttpInfo(league_id, entry_id, SportRatedLeagueEntryUpdate) {
      let postBody = SportRatedLeagueEntryUpdate;
      // verify the required parameter 'league_id' is set
      if (league_id === undefined || league_id === null) {
        throw new Error("Missing the required parameter 'league_id' when calling updateLeagueEntry");
      }
      // verify the required parameter 'entry_id' is set
      if (entry_id === undefined || entry_id === null) {
        throw new Error("Missing the required parameter 'entry_id' when calling updateLeagueEntry");
      }
      // verify the required parameter 'SportRatedLeagueEntryUpdate' is set
      if (SportRatedLeagueEntryUpdate === undefined || SportRatedLeagueEntryUpdate === null) {
        throw new Error("Missing the required parameter 'SportRatedLeagueEntryUpdate' when calling updateLeagueEntry");
      }

      let pathParams = {
        'league_id': league_id,
        'entry_id': entry_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SportRatedLeagueEntry;
      return this.apiClient.callApi(
        '/api/v1/rating/{league_id}/entries/{entry_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update League Entry
     * @param {Number} league_id 
     * @param {Number} entry_id 
     * @param {module:model/SportRatedLeagueEntryUpdate} SportRatedLeagueEntryUpdate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SportRatedLeagueEntry}
     */
    updateLeagueEntry(league_id, entry_id, SportRatedLeagueEntryUpdate) {
      return this.updateLeagueEntryWithHttpInfo(league_id, entry_id, SportRatedLeagueEntryUpdate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
