/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BetOutcome.
* @enum {}
* @readonly
*/
export default class BetOutcome {
    
        /**
         * value: "team1"
         * @const
         */
        "team1" = "team1";

    
        /**
         * value: "team2"
         * @const
         */
        "team2" = "team2";

    
        /**
         * value: "draw"
         * @const
         */
        "draw" = "draw";

    

    /**
    * Returns a <code>BetOutcome</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BetOutcome} The enum <code>BetOutcome</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

