/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BetType.
* @enum {}
* @readonly
*/
export default class BetType {
    
        /**
         * value: "fantasy"
         * @const
         */
        "fantasy" = "fantasy";

    
        /**
         * value: "ton"
         * @const
         */
        "ton" = "ton";

    

    /**
    * Returns a <code>BetType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BetType} The enum <code>BetType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

