/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookmakerSearchData from './BookmakerSearchData';
import Status from './Status';

/**
 * The BookmakerSearchResult model module.
 * @module model/BookmakerSearchResult
 * @version 0.1.0
 */
class BookmakerSearchResult {
    /**
     * Constructs a new <code>BookmakerSearchResult</code>.
     * @alias module:model/BookmakerSearchResult
     * @param data {module:model/BookmakerSearchData} 
     */
    constructor(data) { 
        
        BookmakerSearchResult.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>BookmakerSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookmakerSearchResult} obj Optional instance to populate.
     * @return {module:model/BookmakerSearchResult} The populated <code>BookmakerSearchResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookmakerSearchResult();

            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = BookmakerSearchData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookmakerSearchResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookmakerSearchResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BookmakerSearchResult.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `status`
        if (data['status']) { // data not null
          Status.validateJSON(data['status']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          BookmakerSearchData.validateJSON(data['data']);
        }

        return true;
    }


}

BookmakerSearchResult.RequiredProperties = ["data"];

/**
 * @member {module:model/Status} status
 */
BookmakerSearchResult.prototype['status'] = undefined;

/**
 * @member {module:model/BookmakerSearchData} data
 */
BookmakerSearchResult.prototype['data'] = undefined;






export default BookmakerSearchResult;

