/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookmakerMatch from './BookmakerMatch';

/**
 * The BookmakerMatchesList model module.
 * @module model/BookmakerMatchesList
 * @version 0.1.0
 */
class BookmakerMatchesList {
    /**
     * Constructs a new <code>BookmakerMatchesList</code>.
     * @alias module:model/BookmakerMatchesList
     */
    constructor() { 
        
        BookmakerMatchesList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookmakerMatchesList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookmakerMatchesList} obj Optional instance to populate.
     * @return {module:model/BookmakerMatchesList} The populated <code>BookmakerMatchesList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookmakerMatchesList();

            if (data.hasOwnProperty('matches')) {
                obj['matches'] = ApiClient.convertToType(data['matches'], [BookmakerMatch]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookmakerMatchesList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookmakerMatchesList</code>.
     */
    static validateJSON(data) {
        if (data['matches']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['matches'])) {
                throw new Error("Expected the field `matches` to be an array in the JSON data but got " + data['matches']);
            }
            // validate the optional field `matches` (array)
            for (const item of data['matches']) {
                BookmakerMatch.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/BookmakerMatch>} matches
 */
BookmakerMatchesList.prototype['matches'] = undefined;






export default BookmakerMatchesList;

