/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PhaseType.
* @enum {}
* @readonly
*/
export default class PhaseType {
    
        /**
         * value: "live"
         * @const
         */
        "live" = "live";

    
        /**
         * value: "prematch"
         * @const
         */
        "prematch" = "prematch";

    

    /**
    * Returns a <code>PhaseType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PhaseType} The enum <code>PhaseType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

