/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BetOutcome from './BetOutcome';

/**
 * The SportMatchBetCreate model module.
 * @module model/SportMatchBetCreate
 * @version 0.1.0
 */
class SportMatchBetCreate {
    /**
     * Constructs a new <code>SportMatchBetCreate</code>.
     * @alias module:model/SportMatchBetCreate
     * @param match_id {Number} 
     * @param bet_amount {Number} 
     * @param bet_team {module:model/BetOutcome} 
     * @param free_bet_id {Number} 
     */
    constructor(match_id, bet_amount, bet_team, free_bet_id) { 
        
        SportMatchBetCreate.initialize(this, match_id, bet_amount, bet_team, free_bet_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, match_id, bet_amount, bet_team, free_bet_id) { 
        obj['match_id'] = match_id;
        obj['bet_amount'] = bet_amount;
        obj['bet_team'] = bet_team;
        obj['free_bet_id'] = free_bet_id;
    }

    /**
     * Constructs a <code>SportMatchBetCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportMatchBetCreate} obj Optional instance to populate.
     * @return {module:model/SportMatchBetCreate} The populated <code>SportMatchBetCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportMatchBetCreate();

            if (data.hasOwnProperty('match_id')) {
                obj['match_id'] = ApiClient.convertToType(data['match_id'], 'Number');
            }
            if (data.hasOwnProperty('bet_amount')) {
                obj['bet_amount'] = ApiClient.convertToType(data['bet_amount'], 'Number');
            }
            if (data.hasOwnProperty('bet_team')) {
                obj['bet_team'] = BetOutcome.constructFromObject(data['bet_team']);
            }
            if (data.hasOwnProperty('free_bet_id')) {
                obj['free_bet_id'] = ApiClient.convertToType(data['free_bet_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportMatchBetCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportMatchBetCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SportMatchBetCreate.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SportMatchBetCreate.RequiredProperties = ["match_id", "bet_amount", "bet_team", "free_bet_id"];

/**
 * @member {Number} match_id
 */
SportMatchBetCreate.prototype['match_id'] = undefined;

/**
 * @member {Number} bet_amount
 */
SportMatchBetCreate.prototype['bet_amount'] = undefined;

/**
 * @member {module:model/BetOutcome} bet_team
 */
SportMatchBetCreate.prototype['bet_team'] = undefined;

/**
 * @member {Number} free_bet_id
 */
SportMatchBetCreate.prototype['free_bet_id'] = undefined;






export default SportMatchBetCreate;

