/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SportTeam model module.
 * @module model/SportTeam
 * @version 0.1.0
 */
class SportTeam {
    /**
     * Constructs a new <code>SportTeam</code>.
     * @alias module:model/SportTeam
     * @param name {String} 
     * @param sport_id {Number} 
     * @param bookmaker_team_id {Number} 
     */
    constructor(name, sport_id, bookmaker_team_id) { 
        
        SportTeam.initialize(this, name, sport_id, bookmaker_team_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, sport_id, bookmaker_team_id) { 
        obj['name'] = name;
        obj['sport_id'] = sport_id;
        obj['bookmaker_team_id'] = bookmaker_team_id;
    }

    /**
     * Constructs a <code>SportTeam</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportTeam} obj Optional instance to populate.
     * @return {module:model/SportTeam} The populated <code>SportTeam</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportTeam();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('sport_id')) {
                obj['sport_id'] = ApiClient.convertToType(data['sport_id'], 'Number');
            }
            if (data.hasOwnProperty('bookmaker_team_id')) {
                obj['bookmaker_team_id'] = ApiClient.convertToType(data['bookmaker_team_id'], 'Number');
            }
            if (data.hasOwnProperty('icon_url')) {
                obj['icon_url'] = ApiClient.convertToType(data['icon_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportTeam</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportTeam</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SportTeam.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['icon_url'] && !(typeof data['icon_url'] === 'string' || data['icon_url'] instanceof String)) {
            throw new Error("Expected the field `icon_url` to be a primitive type in the JSON string but got " + data['icon_url']);
        }

        return true;
    }


}

SportTeam.RequiredProperties = ["name", "sport_id", "bookmaker_team_id"];

/**
 * @member {String} name
 */
SportTeam.prototype['name'] = undefined;

/**
 * @member {Number} sport_id
 */
SportTeam.prototype['sport_id'] = undefined;

/**
 * @member {Number} bookmaker_team_id
 */
SportTeam.prototype['bookmaker_team_id'] = undefined;

/**
 * @member {String} icon_url
 */
SportTeam.prototype['icon_url'] = undefined;

/**
 * @member {Number} id
 */
SportTeam.prototype['id'] = undefined;






export default SportTeam;

