/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SportRatedLeague model module.
 * @module model/SportRatedLeague
 * @version 0.1.0
 */
class SportRatedLeague {
    /**
     * Constructs a new <code>SportRatedLeague</code>.
     * @alias module:model/SportRatedLeague
     * @param name {String} 
     * @param description {String} 
     * @param icon_url {String} 
     * @param start_time {Number} 
     * @param end_time {Number} 
     */
    constructor(name, description, icon_url, start_time, end_time) { 
        
        SportRatedLeague.initialize(this, name, description, icon_url, start_time, end_time);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, icon_url, start_time, end_time) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['icon_url'] = icon_url;
        obj['start_time'] = start_time;
        obj['end_time'] = end_time;
    }

    /**
     * Constructs a <code>SportRatedLeague</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportRatedLeague} obj Optional instance to populate.
     * @return {module:model/SportRatedLeague} The populated <code>SportRatedLeague</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportRatedLeague();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('icon_url')) {
                obj['icon_url'] = ApiClient.convertToType(data['icon_url'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Number');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportRatedLeague</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportRatedLeague</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SportRatedLeague.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['icon_url'] && !(typeof data['icon_url'] === 'string' || data['icon_url'] instanceof String)) {
            throw new Error("Expected the field `icon_url` to be a primitive type in the JSON string but got " + data['icon_url']);
        }

        return true;
    }


}

SportRatedLeague.RequiredProperties = ["name", "description", "icon_url", "start_time", "end_time"];

/**
 * @member {String} name
 */
SportRatedLeague.prototype['name'] = undefined;

/**
 * @member {String} description
 */
SportRatedLeague.prototype['description'] = undefined;

/**
 * @member {String} icon_url
 */
SportRatedLeague.prototype['icon_url'] = undefined;

/**
 * @member {Number} start_time
 */
SportRatedLeague.prototype['start_time'] = undefined;

/**
 * @member {Number} end_time
 */
SportRatedLeague.prototype['end_time'] = undefined;

/**
 * @member {Number} id
 */
SportRatedLeague.prototype['id'] = undefined;






export default SportRatedLeague;

