/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SportRatedLeagueEntryCreate model module.
 * @module model/SportRatedLeagueEntryCreate
 * @version 0.1.0
 */
class SportRatedLeagueEntryCreate {
    /**
     * Constructs a new <code>SportRatedLeagueEntryCreate</code>.
     * @alias module:model/SportRatedLeagueEntryCreate
     * @param user_id {Number} 
     * @param rated_league_id {Number} 
     * @param reward_id {Number} 
     * @param score {Number} 
     * @param place {Number} 
     */
    constructor(user_id, rated_league_id, reward_id, score, place) { 
        
        SportRatedLeagueEntryCreate.initialize(this, user_id, rated_league_id, reward_id, score, place);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user_id, rated_league_id, reward_id, score, place) { 
        obj['user_id'] = user_id;
        obj['rated_league_id'] = rated_league_id;
        obj['reward_id'] = reward_id;
        obj['score'] = score;
        obj['place'] = place;
    }

    /**
     * Constructs a <code>SportRatedLeagueEntryCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportRatedLeagueEntryCreate} obj Optional instance to populate.
     * @return {module:model/SportRatedLeagueEntryCreate} The populated <code>SportRatedLeagueEntryCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportRatedLeagueEntryCreate();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('rated_league_id')) {
                obj['rated_league_id'] = ApiClient.convertToType(data['rated_league_id'], 'Number');
            }
            if (data.hasOwnProperty('reward_id')) {
                obj['reward_id'] = ApiClient.convertToType(data['reward_id'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = ApiClient.convertToType(data['place'], 'Number');
            }
            if (data.hasOwnProperty('previous_place')) {
                obj['previous_place'] = ApiClient.convertToType(data['previous_place'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportRatedLeagueEntryCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportRatedLeagueEntryCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SportRatedLeagueEntryCreate.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SportRatedLeagueEntryCreate.RequiredProperties = ["user_id", "rated_league_id", "reward_id", "score", "place"];

/**
 * @member {Number} user_id
 */
SportRatedLeagueEntryCreate.prototype['user_id'] = undefined;

/**
 * @member {Number} rated_league_id
 */
SportRatedLeagueEntryCreate.prototype['rated_league_id'] = undefined;

/**
 * @member {Number} reward_id
 */
SportRatedLeagueEntryCreate.prototype['reward_id'] = undefined;

/**
 * @member {Number} score
 */
SportRatedLeagueEntryCreate.prototype['score'] = undefined;

/**
 * @member {Number} place
 */
SportRatedLeagueEntryCreate.prototype['place'] = undefined;

/**
 * @member {Number} previous_place
 */
SportRatedLeagueEntryCreate.prototype['previous_place'] = undefined;






export default SportRatedLeagueEntryCreate;

