/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SportRatedLeagueEntryUpdate model module.
 * @module model/SportRatedLeagueEntryUpdate
 * @version 0.1.0
 */
class SportRatedLeagueEntryUpdate {
    /**
     * Constructs a new <code>SportRatedLeagueEntryUpdate</code>.
     * @alias module:model/SportRatedLeagueEntryUpdate
     * @param score {Number} 
     * @param place {Number} 
     */
    constructor(score, place) { 
        
        SportRatedLeagueEntryUpdate.initialize(this, score, place);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, score, place) { 
        obj['score'] = score;
        obj['place'] = place;
    }

    /**
     * Constructs a <code>SportRatedLeagueEntryUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportRatedLeagueEntryUpdate} obj Optional instance to populate.
     * @return {module:model/SportRatedLeagueEntryUpdate} The populated <code>SportRatedLeagueEntryUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportRatedLeagueEntryUpdate();

            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = ApiClient.convertToType(data['place'], 'Number');
            }
            if (data.hasOwnProperty('previous_place')) {
                obj['previous_place'] = ApiClient.convertToType(data['previous_place'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportRatedLeagueEntryUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportRatedLeagueEntryUpdate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SportRatedLeagueEntryUpdate.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SportRatedLeagueEntryUpdate.RequiredProperties = ["score", "place"];

/**
 * @member {Number} score
 */
SportRatedLeagueEntryUpdate.prototype['score'] = undefined;

/**
 * @member {Number} place
 */
SportRatedLeagueEntryUpdate.prototype['place'] = undefined;

/**
 * @member {Number} previous_place
 */
SportRatedLeagueEntryUpdate.prototype['previous_place'] = undefined;






export default SportRatedLeagueEntryUpdate;

