/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SportFreeBetNft model module.
 * @module model/SportFreeBetNft
 * @version 0.1.0
 */
class SportFreeBetNft {
    /**
     * Constructs a new <code>SportFreeBetNft</code>.
     * @alias module:model/SportFreeBetNft
     * @param address {String} 
     * @param index {Number} 
     * @param value {Number} 
     */
    constructor(address, index, value) { 
        
        SportFreeBetNft.initialize(this, address, index, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, index, value) { 
        obj['address'] = address;
        obj['index'] = index;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>SportFreeBetNft</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportFreeBetNft} obj Optional instance to populate.
     * @return {module:model/SportFreeBetNft} The populated <code>SportFreeBetNft</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportFreeBetNft();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportFreeBetNft</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportFreeBetNft</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SportFreeBetNft.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }


}

SportFreeBetNft.RequiredProperties = ["address", "index", "value"];

/**
 * @member {String} address
 */
SportFreeBetNft.prototype['address'] = undefined;

/**
 * @member {Number} index
 */
SportFreeBetNft.prototype['index'] = undefined;

/**
 * @member {Number} value
 */
SportFreeBetNft.prototype['value'] = undefined;

/**
 * @member {Number} id
 */
SportFreeBetNft.prototype['id'] = undefined;






export default SportFreeBetNft;

