/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BetType from './BetType';
import PhaseType from './PhaseType';

/**
 * The SportMatchUpdate model module.
 * @module model/SportMatchUpdate
 * @version 0.1.0
 */
class SportMatchUpdate {
    /**
     * Constructs a new <code>SportMatchUpdate</code>.
     * @alias module:model/SportMatchUpdate
     */
    constructor() { 
        
        SportMatchUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SportMatchUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportMatchUpdate} obj Optional instance to populate.
     * @return {module:model/SportMatchUpdate} The populated <code>SportMatchUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportMatchUpdate();

            if (data.hasOwnProperty('total_bets')) {
                obj['total_bets'] = ApiClient.convertToType(data['total_bets'], 'Number');
            }
            if (data.hasOwnProperty('total_win_bets')) {
                obj['total_win_bets'] = ApiClient.convertToType(data['total_win_bets'], 'Number');
            }
            if (data.hasOwnProperty('total_earned_tons')) {
                obj['total_earned_tons'] = ApiClient.convertToType(data['total_earned_tons'], 'Number');
            }
            if (data.hasOwnProperty('fee')) {
                obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
            }
            if (data.hasOwnProperty('finished')) {
                obj['finished'] = ApiClient.convertToType(data['finished'], 'Boolean');
            }
            if (data.hasOwnProperty('match_time')) {
                obj['match_time'] = ApiClient.convertToType(data['match_time'], 'Number');
            }
            if (data.hasOwnProperty('phase')) {
                obj['phase'] = ApiClient.convertToType(data['phase'], PhaseType);
            }
            if (data.hasOwnProperty('contract_address')) {
                obj['contract_address'] = ApiClient.convertToType(data['contract_address'], 'String');
            }
            if (data.hasOwnProperty('team1_score')) {
                obj['team1_score'] = ApiClient.convertToType(data['team1_score'], 'Number');
            }
            if (data.hasOwnProperty('team2_score')) {
                obj['team2_score'] = ApiClient.convertToType(data['team2_score'], 'Number');
            }
            if (data.hasOwnProperty('team1_ratio')) {
                obj['team1_ratio'] = ApiClient.convertToType(data['team1_ratio'], 'Number');
            }
            if (data.hasOwnProperty('team2_ratio')) {
                obj['team2_ratio'] = ApiClient.convertToType(data['team2_ratio'], 'Number');
            }
            if (data.hasOwnProperty('draw_ratio')) {
                obj['draw_ratio'] = ApiClient.convertToType(data['draw_ratio'], 'Number');
            }
            if (data.hasOwnProperty('team1_summary')) {
                obj['team1_summary'] = ApiClient.convertToType(data['team1_summary'], 'Number');
            }
            if (data.hasOwnProperty('team2_summary')) {
                obj['team2_summary'] = ApiClient.convertToType(data['team2_summary'], 'Number');
            }
            if (data.hasOwnProperty('draw_summary')) {
                obj['draw_summary'] = ApiClient.convertToType(data['draw_summary'], 'Number');
            }
            if (data.hasOwnProperty('bookmaker_match_id')) {
                obj['bookmaker_match_id'] = ApiClient.convertToType(data['bookmaker_match_id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = BetType.constructFromObject(data['type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportMatchUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportMatchUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['contract_address'] && !(typeof data['contract_address'] === 'string' || data['contract_address'] instanceof String)) {
            throw new Error("Expected the field `contract_address` to be a primitive type in the JSON string but got " + data['contract_address']);
        }

        return true;
    }


}



/**
 * @member {Number} total_bets
 */
SportMatchUpdate.prototype['total_bets'] = undefined;

/**
 * @member {Number} total_win_bets
 */
SportMatchUpdate.prototype['total_win_bets'] = undefined;

/**
 * @member {Number} total_earned_tons
 */
SportMatchUpdate.prototype['total_earned_tons'] = undefined;

/**
 * @member {Number} fee
 */
SportMatchUpdate.prototype['fee'] = undefined;

/**
 * @member {Boolean} finished
 */
SportMatchUpdate.prototype['finished'] = undefined;

/**
 * @member {Number} match_time
 */
SportMatchUpdate.prototype['match_time'] = undefined;

/**
 * @member {module:model/PhaseType} phase
 */
SportMatchUpdate.prototype['phase'] = undefined;

/**
 * @member {String} contract_address
 */
SportMatchUpdate.prototype['contract_address'] = undefined;

/**
 * @member {Number} team1_score
 */
SportMatchUpdate.prototype['team1_score'] = undefined;

/**
 * @member {Number} team2_score
 */
SportMatchUpdate.prototype['team2_score'] = undefined;

/**
 * @member {Number} team1_ratio
 */
SportMatchUpdate.prototype['team1_ratio'] = undefined;

/**
 * @member {Number} team2_ratio
 */
SportMatchUpdate.prototype['team2_ratio'] = undefined;

/**
 * @member {Number} draw_ratio
 */
SportMatchUpdate.prototype['draw_ratio'] = undefined;

/**
 * @member {Number} team1_summary
 */
SportMatchUpdate.prototype['team1_summary'] = undefined;

/**
 * @member {Number} team2_summary
 */
SportMatchUpdate.prototype['team2_summary'] = undefined;

/**
 * @member {Number} draw_summary
 */
SportMatchUpdate.prototype['draw_summary'] = undefined;

/**
 * @member {Number} bookmaker_match_id
 */
SportMatchUpdate.prototype['bookmaker_match_id'] = undefined;

/**
 * @member {module:model/BetType} type
 */
SportMatchUpdate.prototype['type'] = undefined;






export default SportMatchUpdate;

