/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BetType from './BetType';
import PhaseType from './PhaseType';

/**
 * The SportMatch model module.
 * @module model/SportMatch
 * @version 0.1.0
 */
class SportMatch {
    /**
     * Constructs a new <code>SportMatch</code>.
     * @alias module:model/SportMatch
     * @param match_start_time {Number} 
     * @param team1_id {Number} 
     * @param team2_id {Number} 
     * @param sport_id {Number} 
     */
    constructor(match_start_time, team1_id, team2_id, sport_id) { 
        
        SportMatch.initialize(this, match_start_time, team1_id, team2_id, sport_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, match_start_time, team1_id, team2_id, sport_id) { 
        obj['match_start_time'] = match_start_time;
        obj['team1_id'] = team1_id;
        obj['team2_id'] = team2_id;
        obj['sport_id'] = sport_id;
    }

    /**
     * Constructs a <code>SportMatch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SportMatch} obj Optional instance to populate.
     * @return {module:model/SportMatch} The populated <code>SportMatch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SportMatch();

            if (data.hasOwnProperty('tournament_id')) {
                obj['tournament_id'] = ApiClient.convertToType(data['tournament_id'], 'Number');
            }
            if (data.hasOwnProperty('match_start_time')) {
                obj['match_start_time'] = ApiClient.convertToType(data['match_start_time'], 'Number');
            }
            if (data.hasOwnProperty('match_time')) {
                obj['match_time'] = ApiClient.convertToType(data['match_time'], 'Number');
            }
            if (data.hasOwnProperty('finished')) {
                obj['finished'] = ApiClient.convertToType(data['finished'], 'Boolean');
            }
            if (data.hasOwnProperty('fantasy')) {
                obj['fantasy'] = ApiClient.convertToType(data['fantasy'], 'Boolean');
            }
            if (data.hasOwnProperty('phase')) {
                obj['phase'] = ApiClient.convertToType(data['phase'], PhaseType);
            }
            if (data.hasOwnProperty('team1_id')) {
                obj['team1_id'] = ApiClient.convertToType(data['team1_id'], 'Number');
            }
            if (data.hasOwnProperty('team2_id')) {
                obj['team2_id'] = ApiClient.convertToType(data['team2_id'], 'Number');
            }
            if (data.hasOwnProperty('bookmaker_match_id')) {
                obj['bookmaker_match_id'] = ApiClient.convertToType(data['bookmaker_match_id'], 'Number');
            }
            if (data.hasOwnProperty('team1_score')) {
                obj['team1_score'] = ApiClient.convertToType(data['team1_score'], 'Number');
            }
            if (data.hasOwnProperty('team2_score')) {
                obj['team2_score'] = ApiClient.convertToType(data['team2_score'], 'Number');
            }
            if (data.hasOwnProperty('team1_ratio')) {
                obj['team1_ratio'] = ApiClient.convertToType(data['team1_ratio'], 'Number');
            }
            if (data.hasOwnProperty('team2_ratio')) {
                obj['team2_ratio'] = ApiClient.convertToType(data['team2_ratio'], 'Number');
            }
            if (data.hasOwnProperty('draw_ratio')) {
                obj['draw_ratio'] = ApiClient.convertToType(data['draw_ratio'], 'Number');
            }
            if (data.hasOwnProperty('sport_id')) {
                obj['sport_id'] = ApiClient.convertToType(data['sport_id'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('total_bets')) {
                obj['total_bets'] = ApiClient.convertToType(data['total_bets'], 'Number');
            }
            if (data.hasOwnProperty('total_win_bets')) {
                obj['total_win_bets'] = ApiClient.convertToType(data['total_win_bets'], 'Number');
            }
            if (data.hasOwnProperty('total_earned_tons')) {
                obj['total_earned_tons'] = ApiClient.convertToType(data['total_earned_tons'], 'Number');
            }
            if (data.hasOwnProperty('fee')) {
                obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = BetType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('team1_summary')) {
                obj['team1_summary'] = ApiClient.convertToType(data['team1_summary'], 'Number');
            }
            if (data.hasOwnProperty('team2_summary')) {
                obj['team2_summary'] = ApiClient.convertToType(data['team2_summary'], 'Number');
            }
            if (data.hasOwnProperty('draw_summary')) {
                obj['draw_summary'] = ApiClient.convertToType(data['draw_summary'], 'Number');
            }
            if (data.hasOwnProperty('contract_address')) {
                obj['contract_address'] = ApiClient.convertToType(data['contract_address'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SportMatch</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SportMatch</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SportMatch.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['contract_address'] && !(typeof data['contract_address'] === 'string' || data['contract_address'] instanceof String)) {
            throw new Error("Expected the field `contract_address` to be a primitive type in the JSON string but got " + data['contract_address']);
        }

        return true;
    }


}

SportMatch.RequiredProperties = ["match_start_time", "team1_id", "team2_id", "sport_id"];

/**
 * @member {Number} tournament_id
 */
SportMatch.prototype['tournament_id'] = undefined;

/**
 * @member {Number} match_start_time
 */
SportMatch.prototype['match_start_time'] = undefined;

/**
 * @member {Number} match_time
 */
SportMatch.prototype['match_time'] = undefined;

/**
 * @member {Boolean} finished
 * @default false
 */
SportMatch.prototype['finished'] = false;

/**
 * @member {Boolean} fantasy
 * @default false
 */
SportMatch.prototype['fantasy'] = false;

/**
 * @member {module:model/PhaseType} phase
 */
SportMatch.prototype['phase'] = undefined;

/**
 * @member {Number} team1_id
 */
SportMatch.prototype['team1_id'] = undefined;

/**
 * @member {Number} team2_id
 */
SportMatch.prototype['team2_id'] = undefined;

/**
 * @member {Number} bookmaker_match_id
 */
SportMatch.prototype['bookmaker_match_id'] = undefined;

/**
 * @member {Number} team1_score
 */
SportMatch.prototype['team1_score'] = undefined;

/**
 * @member {Number} team2_score
 */
SportMatch.prototype['team2_score'] = undefined;

/**
 * @member {Number} team1_ratio
 */
SportMatch.prototype['team1_ratio'] = undefined;

/**
 * @member {Number} team2_ratio
 */
SportMatch.prototype['team2_ratio'] = undefined;

/**
 * @member {Number} draw_ratio
 */
SportMatch.prototype['draw_ratio'] = undefined;

/**
 * @member {Number} sport_id
 */
SportMatch.prototype['sport_id'] = undefined;

/**
 * @member {Number} id
 */
SportMatch.prototype['id'] = undefined;

/**
 * @member {Number} total_bets
 */
SportMatch.prototype['total_bets'] = undefined;

/**
 * @member {Number} total_win_bets
 */
SportMatch.prototype['total_win_bets'] = undefined;

/**
 * @member {Number} total_earned_tons
 */
SportMatch.prototype['total_earned_tons'] = undefined;

/**
 * @member {Number} fee
 */
SportMatch.prototype['fee'] = undefined;

/**
 * @member {module:model/BetType} type
 */
SportMatch.prototype['type'] = undefined;

/**
 * @member {Number} team1_summary
 */
SportMatch.prototype['team1_summary'] = undefined;

/**
 * @member {Number} team2_summary
 */
SportMatch.prototype['team2_summary'] = undefined;

/**
 * @member {Number} draw_summary
 */
SportMatch.prototype['draw_summary'] = undefined;

/**
 * @member {String} contract_address
 */
SportMatch.prototype['contract_address'] = undefined;






export default SportMatch;

