/**
 * BetCoffee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserRead model module.
 * @module model/UserRead
 * @version 0.1.0
 */
class UserRead {
    /**
     * Constructs a new <code>UserRead</code>.
     * @alias module:model/UserRead
     * @param telegram_user_id {Number} 
     */
    constructor(telegram_user_id) { 
        
        UserRead.initialize(this, telegram_user_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, telegram_user_id) { 
        obj['telegram_user_id'] = telegram_user_id;
    }

    /**
     * Constructs a <code>UserRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRead} obj Optional instance to populate.
     * @return {module:model/UserRead} The populated <code>UserRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRead();

            if (data.hasOwnProperty('telegram_user_id')) {
                obj['telegram_user_id'] = ApiClient.convertToType(data['telegram_user_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserRead.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

UserRead.RequiredProperties = ["telegram_user_id"];

/**
 * @member {Number} telegram_user_id
 */
UserRead.prototype['telegram_user_id'] = undefined;






export default UserRead;

